version: '3.9'

services:

  rabbitmq3:
    image: rabbitmq:3.9.7-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS-guest}
    ports:
      - ${AMPQ_PORT-5672}:5672
      - ${RABBITMQ_MNGMNT_PORT-15672}:15672
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app #local changes apply to both sides
    links:
      - rabbitmq3
    depends_on:
      - rabbitmq3